financial_speed/urls.py
from django.contrib import admin
from django.urls import path, include
from transactions import views
#from django.conf import settings
#from django.conf.urls.static import static


urlpatterns = [
	path('', views.index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
	path('transactions/', include('transactions.urls', namespace='transactions')),
    path('admin/', admin.site.urls),
]
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transactions/urls.py
from django.urls import path, include
from . import views

app_name = 'transactions'

urlpatterns = [
	path('signup/', views.signup, name='signup'),
	path('cartes/', views.cartes, name='cartes'),
	path('carte/<int:carte_id>/', views.carte, name='carte'),
	path('promo/', views.promo, name="promo"),
	path('transfert/', views.transfert, name='transfert'),
	path('buycrypto/', views.achat_crypto, name='buy'),
	path('sellcrypto/', views.vendre_crypto, name='sell'),
	path('sent/', views.activation_sent_view, name='activation_sent'),
	path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

transactions/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	localite = models.CharField(max_length=200, blank=False)
	sponsor = models.CharField(max_length=100, blank=False)
	avis = models.CharField(max_length=200, blank=True)

	def __str__(self):
		return self.user.last_name


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)

class Carte(models.Model):
	libelle = models.CharField(max_length=100)
	prix = models.IntegerField()
	description = models.CharField(max_length=1000)
	disponible = models.BooleanField(default=True)
	promo = models.BooleanField(default=False)
	picture = models.ImageField('image',upload_to='images/', blank=True)

	class Meta:
		verbose_name = 'Carte'

	def __str__(self):
		return self.libelle

class Commande(models.Model):
	
	CHOICES = [
    ('MARCORY', (
            ('MARCORY SANS FIL +225 58 73 77 63', 'MARCORY SANS FIL +225 58 73 77 63'),
            # ('ES', 'Spain'),
        )
    ),
    ('KOUMASSI', (
            ('MARCORY ETS TONY REMBLAIS COLLEGE COLOMBE +225 07215421', 'MARCORY ETS TONY REMBLAIS COLLEGE COLOMBE +225 07215421'),
            # ('DZ', 'Algeria'),
        )
    ),
    ]
	
	nom = models.CharField(max_length=30)
	prenom = models.CharField(max_length=100)
	telephone = models.CharField(max_length=12)
	relais = models.CharField(max_length=200, blank=True)
	agence = models.CharField(max_length = 100, choices=CHOICES, blank=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	carte = models.ForeignKey(Carte, on_delete=models.CASCADE)
	date_commande = models.DateTimeField(auto_now_add=True)
	retiree = models.BooleanField(default=False)

	class Meta:
		verbose_name = 'Commande'

	def __str__(self):
		return self.nom


class Contact(models.Model):

	nom = models.CharField('nom', max_length=100)
	email = models.EmailField()
	sujet = models.CharField('sujet', max_length=150)
	message = models.CharField('message', max_length=2000)

	class Meta:
		verbose_name = 'Contact'

	def __str__(self):
		return self.nom

transactions/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.forms import ModelForm, EmailInput, TextInput, PasswordInput
from .models import Commande, Contact

class CustomUserCreationForm(UserCreationForm):

	class Meta:

		model = User
		fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')
		widgets = {
            'username': TextInput(attrs={'class': 'form-control'}),
            'email': EmailInput(attrs={'class': 'form-control'}),
            'first_name': TextInput(attrs={'class': 'form-control'}),
            'last_name': TextInput(attrs={'class': 'form-control'}),
            'password1': PasswordInput(attrs={'class': 'form-control'}),
            'password2': PasswordInput(attrs={'class': 'form-control'}),
        }


class CommandeForm(ModelForm):
	class Meta:
		model = Commande
		fields = ('nom','prenom','telephone','relais','agence')


# class ContactForm(ModelForm):
#     class Meta:
#         model = Contact
#         fields = ['nom', 'email', 'sujet', 'message']
#         widgets = {
#             'nom': TextInput(attrs={'class': 'form-control', 'id':'name', 'placeholder': 'Votre nom', 'data-rule':'minlen:4', 'data-msg':'Entrez un nom de 4 caractères minimum'}),
#             'email': EmailInput(attrs={'class': 'form-control', 'id':'email', 'placeholder':'Votre Email', 'data-rule':'email', 'data-msg':'Entrez un email valide '}),
#             'sujet': TextInput(attrs={'class': 'form-control', 'id':'subject', 'placeholder':'Sujet', 'data-rule':'minlen:4', 'data-msg':'Please enter at least 8 chars of subject'}),
#             'message': Textarea(attrs={'class': 'form-control', 'rows':'5', 'data-rule':'required', 'data-msg':'Please write something for us', 'placeholder':'Message'})
#         }

transactions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.db import transaction, IntegrityError
from django.contrib.auth.decorators import login_required
# UserModel = get_user_model()
from .forms import CustomUserCreationForm, CommandeForm
from .tokens import account_activation_token
from .models import Commande, Carte, Contact

# Create your views here.

def index(request):

	return render(request, 'index.html')

def activation_sent_view(request):
    return render(request, 'activation_sent.html')


@transaction.atomic
def signup(request):
	
	if request.method == 'POST':

		form = CustomUserCreationForm(request.POST)
		if form.is_valid():
			user = form.save(commit=False)
			user.is_active = False
			user.save()
			mail_subject = 'Activate your account'
			current_site = get_current_site(request)
			message = render_to_string('acc_activate_email.html', {
				'user' : user,
				'domain' : current_site.domain,
				'uid' : urlsafe_base64_encode(force_bytes(user.pk)),
				'token' : default_token_generator.make_token(user),
			})
			to_email = form.cleaned_data['email']
			email = EmailMessage(
				mail_subject, message, to=[to_email]
				)
			email.send()
			return redirect('transactions:activation_sent')

	else:
		form = CustomUserCreationForm()

	return render(request, 'signup.html', {'form': form})

def activate(request, uidb64, token):
	try:

		uid = urlsafe_base64_decode(uidb64).decode()
		user = User.objects.get(pk=uid)

	except(TypeError, ValueError, OverflowError, User.DoesNotExist):
		user = None
	if user is not None and default_token_generator.check_token(user, token):

		user.is_active = True
		user.save()
		login(request, user)
		return redirect('index')

	else:

		return render(request, 'activation_invalid.html')



def cartes(request):
    cartes = Carte.objects.filter(disponible=True)
    context = {
        'cartes':cartes
    }
    return render(request, 'cartes.html', context)

@login_required(login_url = 'login')
@transaction.atomic
def carte(request, carte_id):

    carte = get_object_or_404(Carte, pk=carte_id)
    user = request.user
    context = {
        'user_id':user.id,
        'carte_id':carte.id,
        'libelle':carte.libelle,
        'prix' : carte.prix,
        'picture': carte.picture.url,
        'description': carte.description,
    }

    if request.method == 'POST':

        form = CommandeForm(request.POST)
        if form.is_valid():
            agence=form.cleaned_data['agence']
            relais=form.cleaned_data['relais']
            nom=form.cleaned_data['nom']
            prenom=form.cleaned_data['prenom']
            telephone=form.cleaned_data['telephone']
            try:
                with transaction.atomic():
                    carte=get_object_or_404(Carte, pk=carte_id)
                    c=Commande.objects.create(
                    agence=agence,
                    relais = relais,
                    nom=nom,
                    prenom=prenom,
                    carte=carte,
                    telephone=telephone,
                    user=user
                    )
                    email = EmailMessage(
                        subject = 'Commande',
                        from_email = 'noreply@financial-speed.com',
                        body = """Une nouvelle commande a été enregistrée. Connectez-vous à  l'admin pour les details de la commande""",
                        to = ['noreply@financial-speed.com',],
                        headers={'Content-Type': 'text/plain'},
                    )
                    email.send()
                    email1 = EmailMessage(
                        subject = 'Achat chez financial-speed.com',
                        from_email = 'noreply@financial-speed.com',
                        body = "Votre opération a été validée. rendez-vous en agence pour retirer votre carte",
                        to = [user.email],
                        headers={'Content-Type': 'text/plain'},
                    )
                    email1.send()
                    return render(request, 'merci.html', {'agence' : agence})
            except  IntegrityError:
                form.errors['internal'] = "Une erreur est survenue.Merci de reprendre votre commande"       
    else:
        form = CommandeForm()
    context['errors'] = form.errors.items() 
    context['form'] = form
    return render(request, 'carte.html', context)


def promo(request):
    cartes = Carte.objects.filter(promo=True)
    context = {
        'cartes_promo' : cartes,
    }
    return render(request, 'promotion.html', context)

# @login_required(login_url = 'transactions:login')
def transfert(request):
    return render(request, 'transfert.html')


def achat_crypto(request):
    return render(request, 'crypto_achat.html')

def vendre_crypto(request):
    return render(request, 'vendre_crypto.html')

transactions/templates/acc_activate_email.html
{% autoescape off %}
	Salut {{ user.username }},
	S'il vous plait cliquez sur le lien ou copiez le dans la barre d'adresse pour confirmer votre inscription.
	
	http://{{ domain }}{% url 'transactions:activate' uidb64=uid token=token %}

	Si vous pensez que ce n'est pas vous , alors ignorez juste ce message.
{% endautoescape %}

transactions/templates/activation_invalid.html
{% extends 'base.html' %}
{% block content %}
	<div class="row" style="margin-top: 110px;">
		<p class="col-md-12 text-danger text-center">
			Lien invalide!!
		</p>
	</div>
{% endblock %}

transactions/templates/activation_sent.html
{% extends 'base.html' %}
{% block content %}
	<div class="row" style="margin-top: 110px;">
		<p class="col-md-12 text-info text-center">
		Lien d'activation envoyé! s'il vous plait consultez votre boite mail.
	</p>
	</div>	
{% endblock %}

transactions/templates/base.html
<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}{% endblock %}</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">
  {% load static %}
  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'transactions/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'transactions/assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'transactions/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'transactions/assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'transactions/assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'transactions/assets/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'transactions/assets/css/style.css' %}" rel="stylesheet">

  <style type="text/css">
    .asteriskField {
      display: none;
    }
    .form-text {
      display: none;
    }
  </style>

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container-fluid d-flex">

      <div class="logo mr-auto">
        <h1 class="text-light"><a href=""><span>FISP</span><img src="{% static 'transactions/assets/img/logo.png' %}" alt="Financial-Speed" class="img-fluid"></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class=""><a href="{% url 'index' %}">Accueil</a></li>
          <li class="drop-down"><a href="">Cartes prepayees</a>
            <ul>
              <li><a href="{% url 'transactions:promo' %}">Promotions</a></li>
              <li><a href="{% url 'transactions:cartes' %}">Toutes nos cartes</a></li>
            </ul>
          </li>
          <li class="drop-down"><a href="{% url 'transactions:buy' %}">Cryptomonnaie</a>
            <ul>
              <li><a href="{% url 'transactions:buy' %}">Acheter</a></li>
              <li><a href="{% url 'transactions:sell' %}">Vendre</a></li>
            </ul>
          </li>
          <li class=""><a href="{% url 'transactions:transfert' %}">Transfert d'argent</a></li>
          {% if user.is_authenticated %}
            <li class="get-started"><a href="{% url 'logout' %}">Deconnexion</a></li>
            <li class="get-started drop-down"><a href="">Compte</a>
              <ul>
                <li><a style="color: white;" href="#">Sponsors</a></li>
                <li><a style="color: white;" href="#">Opérations</a></li>
                <li><a style="color: white;" href="#">Informations</a></li>
                <li><a style="color: white;" href="{% url 'password_change' %}">Mot de passe</a></li>
              </ul>
            </li>
          {% else %}
            <li class="get-started"><a href="{% url 'login' %}">Login</a></li>
            <li class="get-started"><a href="{% url 'transactions:signup' %}">S'inscrire</a></li>
          {% endif %}
        </ul>
      </nav><!-- .nav-menu -->

    </div>
  </header><!-- End Header -->

    <div class="container" style="margin-top: 72px;">
      {% block content %}{% endblock %}
    </div>

  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-newsletter" data-aos="fade-up">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-6">
            <h4>Souscrire à notre Newsletter</h4>
            <p>Soyez informez de nos actualités, produits, offres, promotions.</p>
            <form action="" method="post">
              <input type="email" name="email" placeholder="votre email"><input type="submit" value="Souscrire">
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact" data-aos="fade-up" data-aos-delay="100">
            <h3>Financial-Speed</h3>
            <p>
              Sogefiha <br>
              Abidjan, Koumassi<br>
              Cote d'ivoire <br><br>
              <strong>Numero :</strong> +225 49 70 61 61/ 62 62<br>
              <strong>Email:</strong> contact@financial-speed.com<br>
            </p>
          </div>

          <div class="col-lg-3 col-md-6 footer-links" data-aos="fade-up" data-aos-delay="200">
            <h4>Liens utiles</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Cartes prépayées</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Cryptomonnaie</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Transfert d'argent</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Devenir partenaire</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Conditions d'utilisation</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links" data-aos="fade-up" data-aos-delay="300">
            <h4>Nos Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Cartes prépayées</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Cryptomonnaie</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Transfert d'argent</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Sécurité informatique et électronique</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Billeterie, hotelerie, immobiler</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links" data-aos="fade-up" data-aos-delay="400">
            <h4>Nos réseaux sociaux</h4>
            <p>Suivez-nous sur nos réseaux sociaux</p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
              <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
              <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
              <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="container py-4">
      <div class="copyright">
        &copy; Copyright <strong><span>Financial-Speed</span></strong>. Tous droits réservés
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/ninestars-free-bootstrap-3-theme-for-creative/ -->
        developpé par <a href="#">Himalaya Digital</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'transactions/assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'transactions/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'transactions/assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'transactions/assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'transactions/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'transactions/assets/vendor/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'transactions/assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'transactions/assets/vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'transactions/assets/js/main.js' %}"></script>

</body>

</html>

transactions/templates/carte.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
	<h1 class="col-md-12 text-center text-info">Achetez votre carte</h1>
	<div class="col-md-6">
	  <img class="text text-center" src="{{ picture }}" alt="{{ libelle }}" class="img-responsive">
	  <p class="text text-bold"> Prix : <span style="font-weight: bold;">{{ prix }} FCFA</span> </p>
	  <p style="text-align: justify;">
	  	{{ description }}
	  </p>
	</div>
	<div class="col-md-6">
		<form method="POST" action="{% url 'transactions:carte' carte_id=carte_id %}">
			{% csrf_token %}
			{% for field in form %}
				<p>
					{{ field.label_tag }}<br>
					{{ field }}
				</p>
			{% endfor %}
			<button  type="submit" class="btn btn-success">COMMANDER</button>
		</form>
		{% autoescape off %}
			{% if errors %}
				{% for error in errors %}
				<p style="color: red;">{{ error }}</p>
				{% endfor %}
			{% endif %}
		{% endautoescape %}
	</div>
</div>
{% endblock %}

transactions/templates/cartes.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row">
	<h1 class=" col-md-12 text text-center text-info">Toutes nos cartes</h1>
	{% for carte in cartes %}
	<div class="col-sm-4 text-center ">
		<a href="{% url 'transactions:carte' carte_id=carte.id %}">
			<img class="img-responsive" src="{{ carte.picture.url }}" alt="{{ carte.libelle }}">
		</a>
		<p style="color: color: #f33c1f;">
			{{ carte.libelle }}<br><a href=""><a href="{% url 'transactions:carte' carte_id=carte.id %}">Ajouter au panier</a>	
		</p>
		</div>
		{% if forloop.counter|divisibleby:3 %}<div class="clearfix"></div>{% endif %}
		{% endfor %}		
	</div>
</div>
		
{% endblock %}

transactions/templates/crypto_achat.html
{% extends 'base.html' %}

{% block content  %}
	<div class="row">
		<div class="col-md-12">
			<h1 class="text-center " style="color: #f33c1f">Acheter de la cryptomonnaie </h1>
			<form method="post">
				<div class="form-group">
					<label for="adr">Votre adresse : </label>
					<input type="text" name="adr" id="adr" placeholder="Adresse de votre portefeuille" class="form-control">
				</div>
				<div class="form-group">
					<label for='montant'>Quantité : </label>
					<input type="number" name="montant" placeholder="Quantité à acheter" class="form-control">
				</div>
				<div class="form-group">
					<label for="crypto">Choisissez une monnaie</label>
					<select class="form-control" id="crypto">
						<option value="BTC">BTC</option>
						<option value="Bitcoin cash">Bitcoin cash</option>
						<option value="ether">Ether</option>
						<option value="stellar">Stellar</option>
					</select>
				</div>
				<div class="form-group">
					<label for="op">Choisissez un operateur</label>
					<select class="form-control" id="op">
						<option value="orange">Orange</option>
						<option value="mtn">MTN</option>
						<option value="moov">MOOV</option>
					</select>
				</div>
				<button type="submit" class="btn-success">ACHETER</button>
			</form>
		</div>
	</div>
{% endblock %}

transactions/templates/merci.html
{% extends 'base.html' %}
{% block content %}
<div class="row" style="margin-top: 110px;">
		<p class="font-weight-bold text-success col-md-12 text-center">
			Merci! Rendez-vous en agence pour retirer votre carte : </br> {{ agence }}
		</p>
</div>
{% endblock %}

transactions/templates/promotion.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
	<h1 class=" col-md-12 text text-center text-info">Nos cartes en promotion</h1>
	{% for carte in cartes_promo %}
	<div class="col-sm-4 text-center ">
		<a href="{% url 'transactions:carte' carte_id=carte.id %}">
			<img class="img-responsive" src="{{ carte.picture.url }}" alt="{{ carte.libelle }}">
		</a>
		<p style="color: color: #f33c1f;">
			{{ carte.libelle }}<br><a href=""><a href="{% url 'transactions:carte' carte_id=carte.id %}">Ajouter au panier</a>	
		</p>
		</div>
		{% if forloop.counter|divisibleby:3 %}<div class="clearfix"></div>{% endif %}
		{% endfor %}		
	</div>
</div>
{% endblock %}

transactions/templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card">
      <div class="card-body">
        <h1 class="text text-center text-success">Inscription</h1>
        <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">S'inscrire</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

transactions/templates/transfert.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
	<div class="col-md-12">
		<h1 class="text text-center text-info">Envoyez de l'argent</h1>
		<form method="post">
		<div class="form-group">
			<label for='nom'>Nom complet du destinataire</label><input type="text" name="dest" placeholder="A qui envoyez-vous de l'argent ?" id='nom' class="form-control">
		</div>
		<div class="form-group">
			<label id="numero">Numero ou compte du destinataire</label><input type="number" name="numero" placeholder="Numero de téléphone ou numero du compte vers lequel vous envoyez de l'argent" class="form-control">
		</div>
		
		<button type="submit" class="btn-success">PROCEDER AU TRANSFERT</button>
	</form>
	</div>
</div>
{% endblock %}

transactions/templates/vendre_crypto.html
{% extends 'base.html' %}

{% block content  %}
	<div class="row">
		<div class="col-md-12">
			<h1 class="text-center" style="color: #f33c1f">Vendre vos cryptomonnaie </h1>
			<form method="post">
				<div class="form-group">
					<label for="adr">Votre adresse : </label>
					<input type="text" name="adr" id="adr" placeholder="Adresse de votre portefeuille" class="form-control">
				</div>
				<div class="form-group">
					<label for='montant'>Quantité : </label>
					<input type="number" name="montant" placeholder="Quantité à vendre" class="form-control">
				</div>
				<div class="form-group">
					<label for="crypto">Choisissez une monnaie</label>
					<select class="form-control" id="crypto">
						<option value="BTC">BTC</option>
						<option value="Bitcoin cash">Bitcoin cash</option>
						<option value="ether">Ether</option>
						<option value="stellar">Stellar</option>
					</select>
				</div>
				<div class="form-group">
					<label for="op">Choisissez un operateur</label>
					<select class="form-control" id="op">
						<option value="orange">Orange</option>
						<option value="mtn">MTN</option>
						<option value="moov">MOOV</option>
					</select>
				</div>
				<button type="submit" class="btn-success">VENDRE</button>
			</form>
		</div>
	</div>
{% endblock %}